name: spotify_downloader
description: spotify downloader in flutter


publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  spotify: ^0.7.0
  youtube_explode_dart: ^1.10.10+2
  permission_handler: ^9.2.0
  path_provider: ^2.0.9
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^0.23.0
  sn_progress_dialog: ^1.0.3
  flutter_ffmpeg: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/icon/ic_launcher.png"
  android: true

flutter:

  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/svg/

 